### ISSUE TITLE
gray background in contact forms

### ISSUE THREAD

**Issue by diomed** [web3templates/stablo-astro#3]
hello 

could you change this not to use that awful gray background in contact forms?

otherwise, theme is excellent

**Comment by surjithctly** [comment]
Do you mean in the contact email you receive in email? It's called [Web3Forms](https://web3forms.com) and it's a standalone service. You can upgrade to Web3Forms Pro to customize the email template.

**Comment by diomed** [comment]
no, I mean in this template.

**Comment by surjithctly** [comment]
Can you show a screenshot? and also tell me what you prefer instead.

**Comment by surjithctly** [comment]
nevermind. Found the issue and fixed it.

**Comment by diomed** [comment]
maybe it's silly , but I guess you should make a new release.

**Comment by surjithctly** [comment]
Sure

**Comment by diomed** [comment]
could you also maybe add switcher icon for black / light background. this dropdown navigation for those two is just blah

**Comment by surjithctly** [comment]
You are free to use the toggle or button. See options for this plugin: https://www.npmjs.com/package/astro-color-scheme

We used dropdown because we have one more option called System. If you do not need that, you can add it as a toggle, checkbox, button etc. Check the docs for more details.
